#!/usr/bin/env bash
# Script to create an RSA key pair with specific requirements

# Creating an RSA key pair named "school", with 4096 bits, protected by the passphrase "betty"
ssh-keygen -t rsa -b 4096 -N "betty" -f school
